# Generated by Django 3.2 on 2022-03-06 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20220306_1049'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
