# Generated by Django 3.2 on 2022-03-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_delete_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='tranding',
            field=models.IntegerField(default=0),
        ),
    ]
