# Generated by Django 3.2 on 2022-03-07 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_blog_post_tranding'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='tranding_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
