# Generated by Django 3.2 on 2022-03-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_blog_post_tranding_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='home_slider',
            field=models.BooleanField(default=False),
        ),
    ]
