# Generated by Django 3.2 on 2022-03-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_alter_blog_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='image_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
