# Generated by Django 3.2 on 2022-03-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobpost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_post',
            name='read',
            field=models.IntegerField(default=0),
        ),
    ]
