# Generated by Django 3.2 on 2022-03-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobpost', '0002_job_post_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='jobs/image'),
        ),
    ]
